// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_octopus_lpos
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-10-27, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `andy-VirtualBox`, CPU: `AMD Ryzen 7 5800H with Radeon Graphics`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/appchain-barnacle
// benchmark
// pallet
// --chain
// dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// pallet_octopus_lpos
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// ./octopus/octopus-pallets/lpos/src/weights.rs
// --template
// ./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_octopus_lpos.
pub trait WeightInfo {
	fn set_history_depth(b: u32, m: u32, ) -> Weight;
	fn force_set_era_payout() -> Weight;
}

/// Weights for pallet_octopus_lpos using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: OctopusLpos CurrentEra (r:1 w:0)
	// Storage: OctopusLpos HistoryDepth (r:1 w:1)
	// Storage: OctopusLpos ErasValidatorReward (r:0 w:1)
	// Storage: OctopusLpos ErasRewardPoints (r:0 w:1)
	// Storage: OctopusLpos ErasStakers (r:0 w:1)
	// Storage: OctopusLpos ErasTotalStake (r:0 w:1)
	// Storage: OctopusLpos ErasStartSessionIndex (r:0 w:1)
	/// The range of component `b` is `[0, 4294967295]`.
	/// The range of component `m` is `[0, 4294967295]`.
	fn set_history_depth(_b: u32, _m: u32, ) -> Weight {
		Weight::from_ref_time(22_213_000 as u64)
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: OctopusLpos EraPayout (r:0 w:1)
	fn force_set_era_payout() -> Weight {
		Weight::from_ref_time(11_196_000 as u64)
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: OctopusLpos CurrentEra (r:1 w:0)
	// Storage: OctopusLpos HistoryDepth (r:1 w:1)
	// Storage: OctopusLpos ErasValidatorReward (r:0 w:1)
	// Storage: OctopusLpos ErasRewardPoints (r:0 w:1)
	// Storage: OctopusLpos ErasStakers (r:0 w:1)
	// Storage: OctopusLpos ErasTotalStake (r:0 w:1)
	// Storage: OctopusLpos ErasStartSessionIndex (r:0 w:1)
	/// The range of component `b` is `[0, 4294967295]`.
	/// The range of component `m` is `[0, 4294967295]`.
	fn set_history_depth(_b: u32, _m: u32, ) -> Weight {
		Weight::from_ref_time(22_213_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(2 as u64))
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
	// Storage: OctopusLpos EraPayout (r:0 w:1)
	fn force_set_era_payout() -> Weight {
		Weight::from_ref_time(11_196_000 as u64)
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
}
