// This file is part of Substrate.

// Copyright (C) 2021 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_octopus_lpos
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2021-12-09, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/debug/node-template
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_octopus_lpos
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --raw
// --output
// ./bin/node-template/octopus-pallets/lpos/src/weights.rs
// --template
// ./.maintain/frame-weight-template.hbs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_octopus_lpos.
pub trait WeightInfo {
	fn set_history_depth(b: u32, m: u32, ) -> Weight;
	fn force_set_era_payout() -> Weight;
}

/// Weights for pallet_octopus_lpos using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: OctopusLpos CurrentEra (r:1 w:0)
	// Storage: OctopusLpos HistoryDepth (r:1 w:1)
	// Storage: OctopusLpos ErasValidatorReward (r:0 w:1)
	// Storage: OctopusLpos ErasRewardPoints (r:0 w:1)
	// Storage: OctopusLpos ErasStakers (r:0 w:1)
	// Storage: OctopusLpos ErasTotalStake (r:0 w:1)
	// Storage: OctopusLpos ErasStartSessionIndex (r:0 w:1)
	fn set_history_depth(_b: u32, _m: u32, ) -> Weight {
		(453_275_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: OctopusLpos EraPayout (r:0 w:1)
	fn force_set_era_payout() -> Weight {
		(81_743_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: OctopusLpos CurrentEra (r:1 w:0)
	// Storage: OctopusLpos HistoryDepth (r:1 w:1)
	// Storage: OctopusLpos ErasValidatorReward (r:0 w:1)
	// Storage: OctopusLpos ErasRewardPoints (r:0 w:1)
	// Storage: OctopusLpos ErasStakers (r:0 w:1)
	// Storage: OctopusLpos ErasTotalStake (r:0 w:1)
	// Storage: OctopusLpos ErasStartSessionIndex (r:0 w:1)
	fn set_history_depth(_b: u32, _m: u32, ) -> Weight {
		(453_275_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: OctopusLpos EraPayout (r:0 w:1)
	fn force_set_era_payout() -> Weight {
		(81_743_000 as Weight)
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
}
