[near]
primary_mainnet_rpc_endpoint = "https://rpc.mainnet.near.org"
primary_testnet_rpc_endpoint = "https://rpc.testnet.near.org"
secondary_mainnet_rpc_endpoint = "https://near-mainnet.infura.io/v3/dabe9e95376540b083ae09909ea7c576"
secondary_testnet_rpc_endpoint = "https://near-testnet.infura.io/v3/dabe9e95376540b083ae09909ea7c576"