// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_octopus_appchain
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-09-16, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `andy-VirtualBox`, CPU: `AMD Ryzen 7 5800H with Radeon Graphics`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/debug/appchain-barnacle
// benchmark
// pallet
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_octopus_appchain
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// ./octopus/octopus-pallets/appchain/src/weights.rs
// --template
// ./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_octopus_appchain.
pub trait WeightInfo {
	fn force_set_is_activated() -> Weight;
	fn force_set_next_set_id() -> Weight;
	fn force_set_planned_validators(b: u32, ) -> Weight;
	fn lock() -> Weight;
	fn mint_asset() -> Weight;
	fn burn_asset() -> Weight;
	fn set_token_id() -> Weight;
	fn force_unlock() -> Weight;
	fn lock_nft() -> Weight;
	fn delete_token_id() -> Weight;
	fn submit_observations(b: u32, ) -> Weight;
	fn force_set_next_notification_id() -> Weight;
	fn force_mint_asset() -> Weight;
	fn force_unlock_nft() -> Weight;
}

/// Weights for pallet_octopus_appchain using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: OctopusAppchain IsActivated (r:0 w:1)
	fn force_set_is_activated() -> Weight {
		(200_666_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: OctopusAppchain NextSetId (r:0 w:1)
	fn force_set_next_set_id() -> Weight {
		(426_187_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: OctopusAppchain PlannedValidators (r:0 w:1)
	/// The range of component `b` is `[2, 33]`.
	fn force_set_planned_validators(_b: u32, ) -> Weight {
		(214_685_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: OctopusAppchain IsActivated (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	// Storage: OctopusUpwardMessages MessageQueue (r:1 w:1)
	// Storage: OctopusUpwardMessages Nonce (r:1 w:1)
	fn lock() -> Weight {
		(2_213_016_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: OctopusAssets Asset (r:1 w:1)
	// Storage: OctopusAssets Account (r:1 w:1)
	fn mint_asset() -> Weight {
		(1_852_179_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: OctopusAppchain IsActivated (r:1 w:0)
	// Storage: OctopusAppchain AssetIdByTokenId (r:2 w:0)
	// Storage: OctopusAssets Asset (r:1 w:1)
	// Storage: OctopusAssets Account (r:1 w:1)
	// Storage: OctopusUpwardMessages MessageQueue (r:1 w:1)
	// Storage: OctopusUpwardMessages Nonce (r:1 w:1)
	fn burn_asset() -> Weight {
		(2_555_827_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: OctopusAppchain IsActivated (r:1 w:0)
	// Storage: OctopusAppchain AssetIdByTokenId (r:3 w:1)
	fn set_token_id() -> Weight {
		(847_816_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: System Account (r:1 w:1)
	fn force_unlock() -> Weight {
		(1_973_555_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: OctopusAppchain IsActivated (r:1 w:0)
	// Storage: OctopusUniques ClassMetadataOf (r:1 w:0)
	// Storage: OctopusUniques InstanceMetadataOf (r:1 w:0)
	// Storage: OctopusUniques Class (r:1 w:0)
	// Storage: OctopusUniques Asset (r:1 w:1)
	// Storage: OctopusUpwardMessages Nonce (r:1 w:1)
	// Storage: OctopusUpwardMessages MessageQueue (r:1 w:1)
	// Storage: OctopusUniques Account (r:0 w:2)
	// Storage: OctopusUniques ItemPriceOf (r:0 w:1)
	fn lock_nft() -> Weight {
		(2_901_793_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(6 as Weight))
	}
	// Storage: OctopusAppchain AssetIdByTokenId (r:1 w:1)
	fn delete_token_id() -> Weight {
		(373_314_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Session KeyOwner (r:1 w:0)
	// Storage: Session Validators (r:1 w:0)
	// Storage: OctopusAppchain NextSetId (r:1 w:1)
	// Storage: OctopusAppchain Observations (r:2 w:2)
	// Storage: OctopusAppchain Observing (r:2 w:2)
	// Storage: OctopusLpos ActiveEra (r:1 w:0)
	// Storage: OctopusLpos ErasTotalStake (r:1 w:0)
	// Storage: OctopusLpos ErasStakers (r:1 w:0)
	// Storage: OctopusAppchain NextNotificationId (r:1 w:1)
	// Storage: OctopusAppchain AssetIdByTokenId (r:1 w:0)
	// Storage: OctopusAssets Asset (r:1 w:1)
	// Storage: OctopusAssets Account (r:1 w:1)
	// Storage: OctopusAppchain PlannedValidators (r:0 w:1)
	// Storage: OctopusAppchain NotificationHistory (r:0 w:1)
	// Storage: System Account (r:1 w:1)
	/// The range of component `b` is `[2, 10]`.
	fn submit_observations(b: u32, ) -> Weight {
		(708_851_000 as Weight)
			// Standard Error: 7_024_000
			.saturating_add((2_195_843_000 as Weight).saturating_mul(b as Weight))
			.saturating_add(T::DbWeight::get().reads(10 as Weight))
			.saturating_add(T::DbWeight::get().reads((2 as Weight).saturating_mul(b as Weight)))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
			.saturating_add(T::DbWeight::get().writes((3 as Weight).saturating_mul(b as Weight)))
	}
	// Storage: OctopusAppchain NextNotificationId (r:0 w:1)
	fn force_set_next_notification_id() -> Weight {
		(677_469_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: OctopusAssets Asset (r:1 w:1)
	// Storage: OctopusAssets Account (r:1 w:1)
	fn force_mint_asset() -> Weight {
		(1_743_520_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: OctopusUniques Class (r:1 w:0)
	// Storage: OctopusUniques Asset (r:1 w:1)
	// Storage: OctopusUniques Account (r:0 w:2)
	// Storage: OctopusUniques ItemPriceOf (r:0 w:1)
	fn force_unlock_nft() -> Weight {
		(1_949_058_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: OctopusAppchain IsActivated (r:0 w:1)
	fn force_set_is_activated() -> Weight {
		(200_666_000 as Weight)
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: OctopusAppchain NextSetId (r:0 w:1)
	fn force_set_next_set_id() -> Weight {
		(426_187_000 as Weight)
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: OctopusAppchain PlannedValidators (r:0 w:1)
	/// The range of component `b` is `[2, 33]`.
	fn force_set_planned_validators(_b: u32, ) -> Weight {
		(214_685_000 as Weight)
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: OctopusAppchain IsActivated (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	// Storage: OctopusUpwardMessages MessageQueue (r:1 w:1)
	// Storage: OctopusUpwardMessages Nonce (r:1 w:1)
	fn lock() -> Weight {
		(2_213_016_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	// Storage: OctopusAssets Asset (r:1 w:1)
	// Storage: OctopusAssets Account (r:1 w:1)
	fn mint_asset() -> Weight {
		(1_852_179_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: OctopusAppchain IsActivated (r:1 w:0)
	// Storage: OctopusAppchain AssetIdByTokenId (r:2 w:0)
	// Storage: OctopusAssets Asset (r:1 w:1)
	// Storage: OctopusAssets Account (r:1 w:1)
	// Storage: OctopusUpwardMessages MessageQueue (r:1 w:1)
	// Storage: OctopusUpwardMessages Nonce (r:1 w:1)
	fn burn_asset() -> Weight {
		(2_555_827_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(7 as Weight))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
	}
	// Storage: OctopusAppchain IsActivated (r:1 w:0)
	// Storage: OctopusAppchain AssetIdByTokenId (r:3 w:1)
	fn set_token_id() -> Weight {
		(847_816_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: System Account (r:1 w:1)
	fn force_unlock() -> Weight {
		(1_973_555_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: OctopusAppchain IsActivated (r:1 w:0)
	// Storage: OctopusUniques ClassMetadataOf (r:1 w:0)
	// Storage: OctopusUniques InstanceMetadataOf (r:1 w:0)
	// Storage: OctopusUniques Class (r:1 w:0)
	// Storage: OctopusUniques Asset (r:1 w:1)
	// Storage: OctopusUpwardMessages Nonce (r:1 w:1)
	// Storage: OctopusUpwardMessages MessageQueue (r:1 w:1)
	// Storage: OctopusUniques Account (r:0 w:2)
	// Storage: OctopusUniques ItemPriceOf (r:0 w:1)
	fn lock_nft() -> Weight {
		(2_901_793_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(7 as Weight))
			.saturating_add(RocksDbWeight::get().writes(6 as Weight))
	}
	// Storage: OctopusAppchain AssetIdByTokenId (r:1 w:1)
	fn delete_token_id() -> Weight {
		(373_314_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: Session KeyOwner (r:1 w:0)
	// Storage: Session Validators (r:1 w:0)
	// Storage: OctopusAppchain NextSetId (r:1 w:1)
	// Storage: OctopusAppchain Observations (r:2 w:2)
	// Storage: OctopusAppchain Observing (r:2 w:2)
	// Storage: OctopusLpos ActiveEra (r:1 w:0)
	// Storage: OctopusLpos ErasTotalStake (r:1 w:0)
	// Storage: OctopusLpos ErasStakers (r:1 w:0)
	// Storage: OctopusAppchain NextNotificationId (r:1 w:1)
	// Storage: OctopusAppchain AssetIdByTokenId (r:1 w:0)
	// Storage: OctopusAssets Asset (r:1 w:1)
	// Storage: OctopusAssets Account (r:1 w:1)
	// Storage: OctopusAppchain PlannedValidators (r:0 w:1)
	// Storage: OctopusAppchain NotificationHistory (r:0 w:1)
	// Storage: System Account (r:1 w:1)
	/// The range of component `b` is `[2, 10]`.
	fn submit_observations(b: u32, ) -> Weight {
		(708_851_000 as Weight)
			// Standard Error: 7_024_000
			.saturating_add((2_195_843_000 as Weight).saturating_mul(b as Weight))
			.saturating_add(RocksDbWeight::get().reads(10 as Weight))
			.saturating_add(RocksDbWeight::get().reads((2 as Weight).saturating_mul(b as Weight)))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes((3 as Weight).saturating_mul(b as Weight)))
	}
	// Storage: OctopusAppchain NextNotificationId (r:0 w:1)
	fn force_set_next_notification_id() -> Weight {
		(677_469_000 as Weight)
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: OctopusAssets Asset (r:1 w:1)
	// Storage: OctopusAssets Account (r:1 w:1)
	fn force_mint_asset() -> Weight {
		(1_743_520_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: OctopusUniques Class (r:1 w:0)
	// Storage: OctopusUniques Asset (r:1 w:1)
	// Storage: OctopusUniques Account (r:0 w:2)
	// Storage: OctopusUniques ItemPriceOf (r:0 w:1)
	fn force_unlock_nft() -> Weight {
		(1_949_058_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
	}
}
