[package]
name = "pallet-octopus-lpos"
version = "3.0.0-pre.0"
edition = "2018"
authors = ["Parity Technologies <admin@parity.io>", "Octopus Network <hi@oct.network>"]
license = "Apache-2.0"
homepage = "https://oct.network"
repository = "https://github.com/octopus-network/octopus-pallets.git"
description = "FRAME pallet LPoS"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
static_assertions = "1.1.0"
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
sp-std = { version = "3.0.0", default-features = false }
sp-io ={ version = "3.0.0", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }
sp-staking = { version = "3.0.0", default-features = false }
frame-support = { version = "3.0.0", default-features = false }
frame-system = { version = "3.0.0", default-features = false }
pallet-session = { version = "3.0.0", default-features = false }
pallet-authorship = { version = "3.0.0", default-features = false }
sp-application-crypto = { version = "3.0.0", default-features = false }
log = { version = "0.4.14", default-features = false }
paste = "1.0"
pallet-octopus-support = { default-features = false, path = "../support" }

# Optional imports for benchmarking
frame-benchmarking = { version = "3.1.0", default-features = false, optional = true }
rand_chacha = { version = "0.2", default-features = false, optional = true }

[dev-dependencies]
sp-storage = { version = "3.0.0" }
sp-tracing = { version = "3.0.0" }
sp-core = { version = "3.0.0" }
pallet-balances = { version = "3.0.0" }
pallet-timestamp = { version = "3.0.0" }
substrate-test-utils = { version = "3.0.0" }
frame-benchmarking = { version = "3.1.0" }
rand_chacha = { version = "0.2" }
parking_lot = "0.11.1"
hex = "0.4"

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-std/std",
	"sp-io/std",
	"frame-support/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-session/std",
	"frame-system/std",
	"pallet-authorship/std",
	"sp-application-crypto/std",
	"log/std",
	"pallet-octopus-support/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"rand_chacha",
]
try-runtime = ["frame-support/try-runtime"]
