// This file is part of Substrate.

// Copyright (C) 2021 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_octopus_upward_messages
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2021-11-25, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/debug/node-template
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_octopus_upward_messages
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --raw
// --output
// ./bin/node-template/octopus-pallets/upward-messages/src/weights.rs
// --template
// ./.maintain/frame-weight-template.hbs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_octopus_upward_messages.
pub trait WeightInfo {
	fn on_initialize(m: u32, p: u32, ) -> Weight;
}

/// Weights for pallet_octopus_upward_messages using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: OctopusUpwardMessages MessageQueue (r:1 w:1)
	// Storage: System Digest (r:1 w:1)
	fn on_initialize(m: u32, p: u32, ) -> Weight {
		(107_697_000 as Weight)
			// Standard Error: 723_000
			.saturating_add((37_406_000 as Weight).saturating_mul(m as Weight))
			// Standard Error: 21_000
			.saturating_add((1_204_000 as Weight).saturating_mul(p as Weight))
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: OctopusUpwardMessages MessageQueue (r:1 w:1)
	// Storage: System Digest (r:1 w:1)
	fn on_initialize(m: u32, p: u32, ) -> Weight {
		(107_697_000 as Weight)
			// Standard Error: 723_000
			.saturating_add((37_406_000 as Weight).saturating_mul(m as Weight))
			// Standard Error: 21_000
			.saturating_add((1_204_000 as Weight).saturating_mul(p as Weight))
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
}
