name: Check Set-Up & Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main, feature/add-ci, feature/add-chainbridge, feature/add-chainbridge-v1 ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set-Up
        run: sudo apt install -y git clang curl libssl-dev llvm libudev-dev

      - name: Install Rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source ~/.cargo/env
          rustup default nightly
          rustup update nightly
          rustup update stable
          rustup target add wasm32-unknown-unknown --toolchain nightly

      - name: Check Build
        run: |
          SKIP_WASM_BUILD=1 cargo check --release
          
      - name: Check code format
        run: | 
          cargo fmt -- --check
          
      - name: Lint rust sources
        run: |
          git clone --branch master https://github.com/octopus-network/barnacle.git
          cp ./barnacle/Cargo.lock .
          cargo clippy --all-targets --all-features --tests --benches -- -D warnings
          
      - name: Run tests
        run: | 
          cargo test
        
      - name: Check Build for Benchmarking
        run: >
          cargo check --features=runtime-benchmarks --release
